// Maps URL slugs to display-quality labels for breadcrumb UI + BreadcrumbList JSON-LD.
// Lookup is segment-by-segment: a missing entry falls back to the humanizer.

export const SEGMENT_LABELS = {
  // Top-level sections
  'about': 'About',
  'services': 'Services',
  'blog': 'Blog',
  'showcase': 'Showcase',
  'reviews': 'Reviews',
  'contact': 'Contact',
  'faqs': 'FAQs',
  'team': 'Team',
  'press': 'Press',
  'social': 'Social',
  'scholarship': 'Scholarship',
  'near-you': 'Near You',
  'areas-we-serve': 'Areas We Serve',
  'before-and-after': 'Before & After',
  'thank-you': 'Thank You',
  'review': 'Review',
  'get-estimate': 'Get Estimate',
  'privacy-policy': 'Privacy Policy',
  'terms-of-service': 'Terms of Service',

  // About sub-pages
  'why-choose-us': 'Why Choose Us',
  'process': 'Our Process',
  'certifications-and-licenses': 'Certifications & Licenses',
  'warranty': 'Warranty',

  // Counties
  'loudoun-county': 'Loudoun County',
  'fairfax-county': 'Fairfax County',
  'prince-william-county': 'Prince William County',
  'arlington-county': 'Arlington County',
  'stafford-county': 'Stafford County',

  // Service sub-pages
  'new-decks': 'New Decks',
  'deck-replacement': 'Deck Replacement',
  'deck-repair-and-structural-maintenance': 'Deck Repair & Structural Maintenance',
  'deck-resurfacing': 'Deck Resurfacing',
  'deck-maintenance': 'Deck Maintenance',
  'deck-inspection': 'Deck Inspection',
  'deck-washing': 'Deck Washing',
  'deck-stair-lighting': 'Deck Stair Lighting',
  'porches': 'Porches',
  'front-porch': 'Front Porch',
  'open-porch': 'Open Porch',
  'screened-porch': 'Screened Porch',
  'gazebo-pergola': 'Gazebo & Pergola',
  'patios': 'Patios',
  'fence': 'Fence',
  'fence-cleaning': 'Fence Cleaning',
  'fire-pits': 'Fire Pits',
  'trex-railings': 'Trex Railings',
  'trex-calm-shell': 'Trex Calm Shell',
  'under-deck-patios': 'Under-Deck Patios',
  'concrete-washing': 'Concrete Washing',
  'outdoor-washing': 'Outdoor Washing',
  'house-siding-washing': 'House Siding Washing',
  'windows': 'Windows',
  'entry-doors': 'Entry Doors',

  // Canonical city pages (deck-builder-{city}-va)
  'deck-builder-ashburn-va': 'Deck Builder Ashburn, VA',
  'deck-builder-leesburg-va': 'Deck Builder Leesburg, VA',
  'deck-builder-sterling-va': 'Deck Builder Sterling, VA',
  'deck-builder-purcellville-va': 'Deck Builder Purcellville, VA',
  'deck-builder-brambleton-va': 'Deck Builder Brambleton, VA',
  'deck-builder-south-riding-va': 'Deck Builder South Riding, VA',
  'deck-builder-alexandria-va': 'Deck Builder Alexandria, VA',
  'deck-builder-fairfax-va': 'Deck Builder Fairfax, VA',
  'deck-builder-vienna-va': 'Deck Builder Vienna, VA',
  'deck-builder-reston-va': 'Deck Builder Reston, VA',
  'deck-builder-herndon-va': 'Deck Builder Herndon, VA',
  'deck-builder-mclean-va': 'Deck Builder McLean, VA',
  'deck-builder-centreville-va': 'Deck Builder Centreville, VA',
  'deck-builder-chantilly-va': 'Deck Builder Chantilly, VA',
  'deck-builder-falls-church-va': 'Deck Builder Falls Church, VA',
  'deck-builder-burke-va': 'Deck Builder Burke, VA',
  'deck-builder-springfield-va': 'Deck Builder Springfield, VA',
  'deck-builder-oakton-va': 'Deck Builder Oakton, VA',
  'deck-builder-great-falls-va': 'Deck Builder Great Falls, VA',
  'deck-builder-lorton-va': 'Deck Builder Lorton, VA',
  'deck-builder-tysons-va': 'Deck Builder Tysons, VA',
  'deck-builder-manassas-va': 'Deck Builder Manassas, VA',
  'deck-builder-woodbridge-va': 'Deck Builder Woodbridge, VA',
  'deck-builder-haymarket-va': 'Deck Builder Haymarket, VA',
  'deck-builder-gainesville-va': 'Deck Builder Gainesville, VA',
  'deck-builder-bristow-va': 'Deck Builder Bristow, VA',
  'deck-builder-arlington-va': 'Deck Builder Arlington, VA',
  'deck-builder-stafford-va': 'Deck Builder Stafford, VA',
  'deck-builder-loudoun': 'Deck Builders Loudoun',

  // Major content / authority pages
  'deck-cost-calculator': 'Deck Cost Calculator',
  'deck-financing': 'Deck Financing',
  'deck-financing-northern-virginia': 'Deck Financing in Northern Virginia',
  'deck-repair': 'Deck Repair',
  'deck-remodeling': 'Deck Remodeling',
  'deck-repair-loudoun-county': 'Deck Repair in Loudoun County',
  'composite-decks': 'Composite Decks',
  'trex-decks': 'Trex Decks',
  'wood-decks': 'Wood Decks',
  'houzz-deck-projects': 'Houzz Deck Projects',
  'how-much-does-a-deck-cost-northern-virginia': 'How Much Does a Deck Cost in Northern Virginia?',
  'composite-deck-cost-northern-virginia': 'Composite Deck Cost in Northern Virginia',
  'screened-porch-cost-northern-virginia': 'Screened Porch Cost in Northern Virginia',
  'screened-porch-builder-northern-virginia': 'Screened Porch Builder in Northern Virginia',
  'trex-vs-timbertech-vs-azek': 'Trex vs TimberTech vs AZEK',
  'composite-deck-vs-wood-deck-virginia': 'Composite Deck vs Wood Deck in Virginia',
  'does-a-deck-add-value-to-your-home': 'Does a Deck Add Value to Your Home?',
  'hoa-deck-rules-northern-virginia': 'HOA Deck Rules in Northern Virginia',
  'loudoun-county-hoa-deck-rules': 'Loudoun County HOA Deck Rules',
  'deck-vs-patio-which-is-right': 'Deck vs Patio: Which Is Right?',
  'best-time-to-build-a-deck-northern-virginia': 'Best Time to Build a Deck in Northern Virginia',
  'how-to-choose-a-deck-builder-northern-virginia': 'How to Choose a Deck Builder in Northern Virginia',
  'how-long-does-a-composite-deck-last': 'How Long Does a Composite Deck Last?',
  'how-long-to-build-a-deck-northern-virginia': 'How Long to Build a Deck in Northern Virginia',
  'deck-permit-loudoun-county-virginia': 'Deck Permit — Loudoun County, VA',
  'deck-permit-fairfax-county-virginia': 'Deck Permit — Fairfax County, VA',
  'deck-permit-prince-william-county-virginia': 'Deck Permit — Prince William County, VA',
  'outdoor-kitchen-builder-northern-virginia': 'Outdoor Kitchen Builder in Northern Virginia',
  'deck-staining-northern-virginia': 'Deck Staining in Northern Virginia',
  'deck-railing-options-northern-virginia': 'Deck Railing Options in Northern Virginia',
  'porch-vs-deck-which-should-you-build': 'Porch vs Deck: Which Should You Build?',
  'deck-lighting-ideas-northern-virginia': 'Deck Lighting Ideas in Northern Virginia',
  'deck-maintenance-checklist-virginia': 'Deck Maintenance Checklist for Virginia',
  'winterize-your-deck-northern-virginia': 'Winterize Your Deck — Northern Virginia',
  'deck-warranty-guide-northern-virginia': 'Deck Warranty Guide for Northern Virginia',
  'deck-roi-calculator-northern-virginia': 'Deck ROI Calculator for Northern Virginia',
  'deck-materials-comparison-virginia': 'Deck Materials Comparison — Virginia',
  'second-story-deck-builder-northern-virginia': 'Second-Story Deck Builder in Northern Virginia',
  'what-size-deck-should-i-build': 'What Size Deck Should I Build?',
  'porch-repair-vs-replacement-northern-virginia': 'Porch Repair vs Replacement in Northern Virginia',
  'deck-enclosure-ideas-northern-virginia': 'Deck Enclosure Ideas in Northern Virginia',
  'pool-deck-builder-northern-virginia': 'Pool Deck Builder in Northern Virginia',
  'pet-friendly-deck-design': 'Pet-Friendly Deck Design',
  'under-deck-ceiling-ideas': 'Under-Deck Ceiling Ideas',
  'cable-railing-for-decks-northern-virginia': 'Cable Railing for Decks in Northern Virginia',
  'paver-vs-flagstone-patio-northern-virginia': 'Paver vs Flagstone Patio in Northern Virginia',
  'multi-level-deck-builder-northern-virginia': 'Multi-Level Deck Builder in Northern Virginia',
  'how-tariffs-affect-deck-prices-2026': 'How Tariffs Affect Deck Prices in 2026',
  'northern-virginia-deck-building-guide': 'Northern Virginia Deck Building Guide',
  'northern-virginia-deck-cost-report-2026': 'Northern Virginia Deck Cost Report 2026',
  'eco-friendly-composite-decking': 'Eco-Friendly Composite Decking',
  'questions-to-ask-before-building-a-deck': 'Questions to Ask Before Building a Deck',
  'trex-transcend-review-northern-virginia': 'Trex Transcend Review — Northern Virginia',
  'deck-design-ideas-2026': 'Deck Design Ideas 2026',
  'deck-design-ideas-northern-virginia-2026': 'Deck Design Ideas — Northern Virginia 2026',
  'best-deck-stain-sealer-virginia': 'Best Deck Stain & Sealer for Virginia',
  'outdoor-living-trends-northern-virginia-2026': 'Outdoor Living Trends — Northern Virginia 2026',
  'deck-safety-inspection-checklist': 'Deck Safety Inspection Checklist',
  'stamped-concrete-patio-northern-virginia': 'Stamped Concrete Patio in Northern Virginia',
  'pressure-washing-deck-northern-virginia': 'Pressure Washing a Deck in Northern Virginia',
  'deck-resurfacing-vs-replacement': 'Deck Resurfacing vs Replacement',
  'bbb-accredited-deck-builder-virginia': 'BBB-Accredited Deck Builder in Virginia',
  'ldn-decks-reviews-yelp': 'LDN Decks Reviews on Yelp',
};

const humanize = (slug) =>
  slug
    .replace(/-/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());

export function labelFor(segment) {
  return SEGMENT_LABELS[segment] || humanize(segment);
}
